declare const _default: import("vuex").Store<{
    access_token: string;
    refresh_token: string;
    user: {
        avatar: string;
        created_at: string;
        description: string;
        email: string;
        id: number;
        nickname: string;
        role: string;
        updated_at: string;
        username: string;
    };
    initKey: string;
    sidebarOpen: boolean;
    searchEngine: string;
    searchEngineSwitch: boolean;
    tutorialSwitch: string[];
    rssSwitch: boolean;
    siteLoading: boolean;
    needInitialization: boolean;
    hardwareInfo: {};
    isMobile: boolean;
    operateObject: null;
    currentPath: string;
    isViewGird: boolean;
    wallpaperObject: {
        path: null;
        from: string;
    };
    networkStorage: any;
    shortcutData: never[];
    device_id: string;
    access_id: string;
    casaos_lang: string;
    notImportList: never[];
    newAppIds: never[];
    tipsState: never[];
}>;
export default _default;
