name: Release Raw Module

on:
    workflow_call:
      secrets:
        NPM_TOKEN:
          required: true
    push:
        tags:
            - 'v*'
jobs:
    release:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 18.x ]
        steps:
            -   uses: actions/checkout@v3
            -   name: '使用 Use Node.js ${{ matrix.node-version }}'
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node-version }}
                    cache: pnpm
                    registry-url: "https://registry.npmjs.org"
                    
            -   uses: pnpm/action-setup@v2
                name: Install pnpm
                with:
                  version: 9.12.2
                  run_install: false
                  
            -   name: Get pnpm store directory
                shell: bash
                run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
                  
            -   name: '缓存 Cache'
                uses: actions/cache@v3
                id: cache-dependencies
                with:
                   path: ${{ env.STORE_PATH }}
                   key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                   restore-keys: |
                     ${{ runner.os }}-pnpm-store-
                     
            -   name: 'Read the current version number'
                id: version
                uses: zhanghengxin/reading-a-file-of-JSON@ice
                with:
                    path: ./package.json
                    property:
                        version
            -   name: Get version
                id: get_version
                run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
            -   name: '输出 echo artifact'
                run: |
                    echo ${{ steps.version.outputs.value }}
                    echo github ${{ github }}
                    echo github.sha ${{ github.sha }}
                    echo env.VERSION ${{ steps.get_version.outputs.VERSION }}
                    
            - name: Install dependencies
              run: |
                pnpm install
              env:
                NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

            -   run: pnpm build:raw
            -   run: |
                    mksquashfs raw/ icewhale_app.raw
            -   name: '更新 Update release'
                uses: zhanghengxin/git-release-private@ice
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    allow_override: true
                    gzip: false
                    prerelease: true
                    tag: ${{ steps.get_version.outputs.VERSION }}
                    files: ./icewhale_app.raw

            -   name: Upload to oss
                id: upload_to_oss
                uses: tvrcgo/upload-to-oss@master
                with:
                    key-id: ${{ secrets.OSS_KEY_ID }}
                    key-secret: ${{ secrets.OSS_KEY_SECRET }}
                    region: oss-cn-shanghai
                    bucket: casaos
                    assets: |
                        ./icewhale_app.raw:/IceWhaleTech/IceWhale-App-UI/releases/download/${{ steps.get_version.outputs.VERSION }}/icewhale_app-${{ steps.get_version.outputs.VERSION }}.raw
